### ISSUE TITLE
Generate GRPC gateway

### ISSUE THREAD

**Issue by achaphiv** [MTPRM/mtprm-proto#6]
## TODO

Generate:

- [x] golang source
- [x] openapi/swagger definition files
- [x] implement gprc-gateway 
- [x] serve openapi docs with grpc-gateway

Push to another repository (`mtprm-backend-api-grpc-gateway`?) which will separately build the docker image and friends.

Related issue: #8

**Comment by achaphiv** [comment]
Generation done by: 0f8ed972735608b785027d1869b015e535e39c29.

**Comment by achaphiv** [comment]
The grpc-gateway is currently being built into a docker image and pushed to github packages.
